POST http://localhost:5000/api/battery/create HTTP/1.1
Content-Type: application/json

{
  "imagePath": "public/battery/img.png",
  "title": "Автомобільний акумулятор Westa 6CT-63 А 0 RED EFB (WEFB6300LB2)",
  "description": "Автомобільний акумулятор Westa 6CT-63 А 0 RED EFB (WEFB6300LB2) являє собою акумуляторну батарею типу EFB, яка має високу надійність і продуктивність. Місткість акумулятора становить 63 А/год, напруга – 12 Вольтів.",
  "type": "Вантажний",
  "capacity": "63 A*год",
  "work_temp": [
    -20,
    20
  ],
  "work_voltage": [
    0,
    12
  ],
  "isAvailable": true,
  "type_connector": "string",
  "max_amp": "string",
  "date_getting": "2023-05-13",
  "date_write_off": "2023-06-14",
  "suitable_with": [
    "ЗІЛ-130",
    "ЗІЛ-131",
    "КАМАЗ",
    "МАЗ"
  ],
  "isGuarantee": true,
  "guarantee_description": "10 місяців",
  "country": "Україна",
  "count": 32
}